# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'RadarGUI.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1115, 750)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setDocumentMode(False)
        MainWindow.setDockOptions(QtWidgets.QMainWindow.AllowTabbedDocks|QtWidgets.QMainWindow.AnimatedDocks|QtWidgets.QMainWindow.GroupedDragging|QtWidgets.QMainWindow.VerticalTabs)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tabWidget.setFont(font)
        self.tabWidget.setStyleSheet("")
        self.tabWidget.setObjectName("tabWidget")
        self.if_voltage_tab = QtWidgets.QWidget()
        font = QtGui.QFont()
        font.setPointSize(8)
        self.if_voltage_tab.setFont(font)
        self.if_voltage_tab.setObjectName("if_voltage_tab")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.if_voltage_tab)
        self.verticalLayout.setObjectName("verticalLayout")
        self.if_voltage_pgw = IFVoltagePlotWidget(self.if_voltage_tab)
        self.if_voltage_pgw.setObjectName("if_voltage_pgw")
        self.verticalLayout.addWidget(self.if_voltage_pgw)
        self.tabWidget.addTab(self.if_voltage_tab, "")
        self.if_spectrum_tab = QtWidgets.QWidget()
        self.if_spectrum_tab.setObjectName("if_spectrum_tab")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.if_spectrum_tab)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.if_spectrum_pgw = IFSpectrumPlotWidget(self.if_spectrum_tab)
        self.if_spectrum_pgw.setObjectName("if_spectrum_pgw")
        self.verticalLayout_3.addWidget(self.if_spectrum_pgw)
        self.tabWidget.addTab(self.if_spectrum_tab, "")
        self.if_waterfall_tab = QtWidgets.QWidget()
        self.if_waterfall_tab.setObjectName("if_waterfall_tab")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.if_waterfall_tab)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.if_waterfall_pgw = IFWaterfallPlotWidget(self.if_waterfall_tab)
        self.if_waterfall_pgw.setObjectName("if_waterfall_pgw")
        self.verticalLayout_4.addWidget(self.if_waterfall_pgw)
        self.tabWidget.addTab(self.if_waterfall_tab, "")
        self.log_messages_tab = QtWidgets.QWidget()
        self.log_messages_tab.setObjectName("log_messages_tab")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.log_messages_tab)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.log_area = QtWidgets.QPlainTextEdit(self.log_messages_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.log_area.sizePolicy().hasHeightForWidth())
        self.log_area.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.log_area.setFont(font)
        self.log_area.setFocusPolicy(QtCore.Qt.NoFocus)
        self.log_area.setAcceptDrops(False)
        self.log_area.setStyleSheet("color: white;\n"
"background-color: black;")
        self.log_area.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.log_area.setTabChangesFocus(True)
        self.log_area.setReadOnly(True)
        self.log_area.setObjectName("log_area")
        self.verticalLayout_2.addWidget(self.log_area)
        self.tabWidget.addTab(self.log_messages_tab, "")
        self.horizontalLayout_5.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1115, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setEnabled(True)
        self.statusbar.setSizeGripEnabled(True)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.radar_controls_group = QtWidgets.QDockWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radar_controls_group.sizePolicy().hasHeightForWidth())
        self.radar_controls_group.setSizePolicy(sizePolicy)
        self.radar_controls_group.setMinimumSize(QtCore.QSize(930, 160))
        self.radar_controls_group.setMaximumSize(QtCore.QSize(930, 160))
        self.radar_controls_group.setFeatures(QtWidgets.QDockWidget.DockWidgetFloatable|QtWidgets.QDockWidget.DockWidgetMovable)
        self.radar_controls_group.setAllowedAreas(QtCore.Qt.BottomDockWidgetArea|QtCore.Qt.TopDockWidgetArea)
        self.radar_controls_group.setObjectName("radar_controls_group")
        self.dockWidgetContents_3 = QtWidgets.QWidget()
        self.dockWidgetContents_3.setObjectName("dockWidgetContents_3")
        self.gain_gb_2 = QtWidgets.QGroupBox(self.dockWidgetContents_3)
        self.gain_gb_2.setGeometry(QtCore.QRect(13, 0, 176, 129))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gain_gb_2.sizePolicy().hasHeightForWidth())
        self.gain_gb_2.setSizePolicy(sizePolicy)
        self.gain_gb_2.setMinimumSize(QtCore.QSize(160, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.gain_gb_2.setFont(font)
        self.gain_gb_2.setAlignment(QtCore.Qt.AlignCenter)
        self.gain_gb_2.setObjectName("gain_gb_2")
        self.connect_cb = QtWidgets.QComboBox(self.gain_gb_2)
        self.connect_cb.setGeometry(QtCore.QRect(10, 60, 151, 22))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.connect_cb.setFont(font)
        self.connect_cb.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToMinimumContentsLength)
        self.connect_cb.setFrame(True)
        self.connect_cb.setObjectName("connect_cb")
        self.connect_status_le = QtWidgets.QLineEdit(self.gain_gb_2)
        self.connect_status_le.setGeometry(QtCore.QRect(10, 30, 151, 24))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.connect_status_le.setFont(font)
        self.connect_status_le.setAlignment(QtCore.Qt.AlignCenter)
        self.connect_status_le.setObjectName("connect_status_le")
        self.connect_pb = QtWidgets.QPushButton(self.gain_gb_2)
        self.connect_pb.setGeometry(QtCore.QRect(10, 90, 151, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.connect_pb.setFont(font)
        self.connect_pb.setCheckable(True)
        self.connect_pb.setObjectName("connect_pb")
        self.gain_gb = QtWidgets.QGroupBox(self.dockWidgetContents_3)
        self.gain_gb.setGeometry(QtCore.QRect(196, 0, 176, 129))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gain_gb.sizePolicy().hasHeightForWidth())
        self.gain_gb.setSizePolicy(sizePolicy)
        self.gain_gb.setMinimumSize(QtCore.QSize(160, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.gain_gb.setFont(font)
        self.gain_gb.setAlignment(QtCore.Qt.AlignCenter)
        self.gain_gb.setObjectName("gain_gb")
        self.layoutWidget_3 = QtWidgets.QWidget(self.gain_gb)
        self.layoutWidget_3.setGeometry(QtCore.QRect(10, 30, 159, 52))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget_3)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gain_lcd = QtWidgets.QLCDNumber(self.layoutWidget_3)
        self.gain_lcd.setMinimumSize(QtCore.QSize(75, 50))
        self.gain_lcd.setMaximumSize(QtCore.QSize(75, 50))
        self.gain_lcd.setBaseSize(QtCore.QSize(75, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.gain_lcd.setFont(font)
        self.gain_lcd.setSmallDecimalPoint(False)
        self.gain_lcd.setDigitCount(4)
        self.gain_lcd.setObjectName("gain_lcd")
        self.horizontalLayout.addWidget(self.gain_lcd)
        self.gain_dial = QtWidgets.QDial(self.layoutWidget_3)
        self.gain_dial.setMinimumSize(QtCore.QSize(50, 50))
        self.gain_dial.setMaximumSize(QtCore.QSize(50, 50))
        self.gain_dial.setMinimum(0)
        self.gain_dial.setMaximum(10)
        self.gain_dial.setSingleStep(1)
        self.gain_dial.setPageStep(1)
        self.gain_dial.setProperty("value", 0)
        self.gain_dial.setSliderPosition(0)
        self.gain_dial.setWrapping(False)
        self.gain_dial.setNotchesVisible(False)
        self.gain_dial.setObjectName("gain_dial")
        self.horizontalLayout.addWidget(self.gain_dial, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.pulse_length_gb = QtWidgets.QGroupBox(self.dockWidgetContents_3)
        self.pulse_length_gb.setGeometry(QtCore.QRect(379, 0, 177, 129))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pulse_length_gb.sizePolicy().hasHeightForWidth())
        self.pulse_length_gb.setSizePolicy(sizePolicy)
        self.pulse_length_gb.setMinimumSize(QtCore.QSize(160, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.pulse_length_gb.setFont(font)
        self.pulse_length_gb.setAlignment(QtCore.Qt.AlignCenter)
        self.pulse_length_gb.setObjectName("pulse_length_gb")
        self.layoutWidget_5 = QtWidgets.QWidget(self.pulse_length_gb)
        self.layoutWidget_5.setGeometry(QtCore.QRect(10, 30, 159, 52))
        self.layoutWidget_5.setObjectName("layoutWidget_5")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.layoutWidget_5)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.pulse_length_lcd = QtWidgets.QLCDNumber(self.layoutWidget_5)
        self.pulse_length_lcd.setMinimumSize(QtCore.QSize(75, 50))
        self.pulse_length_lcd.setMaximumSize(QtCore.QSize(75, 50))
        self.pulse_length_lcd.setBaseSize(QtCore.QSize(75, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.pulse_length_lcd.setFont(font)
        self.pulse_length_lcd.setSmallDecimalPoint(False)
        self.pulse_length_lcd.setDigitCount(4)
        self.pulse_length_lcd.setSegmentStyle(QtWidgets.QLCDNumber.Filled)
        self.pulse_length_lcd.setProperty("intValue", 0)
        self.pulse_length_lcd.setObjectName("pulse_length_lcd")
        self.horizontalLayout_6.addWidget(self.pulse_length_lcd)
        self.pulse_length_dial = QtWidgets.QDial(self.layoutWidget_5)
        self.pulse_length_dial.setMinimumSize(QtCore.QSize(50, 50))
        self.pulse_length_dial.setMaximumSize(QtCore.QSize(50, 50))
        self.pulse_length_dial.setMaximum(10)
        self.pulse_length_dial.setSingleStep(1)
        self.pulse_length_dial.setPageStep(1)
        self.pulse_length_dial.setProperty("value", 3)
        self.pulse_length_dial.setWrapping(False)
        self.pulse_length_dial.setNotchesVisible(False)
        self.pulse_length_dial.setObjectName("pulse_length_dial")
        self.horizontalLayout_6.addWidget(self.pulse_length_dial)
        self.widget = QtWidgets.QWidget(self.pulse_length_gb)
        self.widget.setGeometry(QtCore.QRect(23, 95, 146, 22))
        self.widget.setObjectName("widget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_4 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.trigger_on_rb = QtWidgets.QRadioButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.trigger_on_rb.setFont(font)
        self.trigger_on_rb.setText("On")
        self.trigger_on_rb.setChecked(True)
        self.trigger_on_rb.setObjectName("trigger_on_rb")
        self.horizontalLayout_3.addWidget(self.trigger_on_rb)
        self.trigger_off_rb = QtWidgets.QRadioButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.trigger_off_rb.setFont(font)
        self.trigger_off_rb.setText("Off")
        self.trigger_off_rb.setObjectName("trigger_off_rb")
        self.horizontalLayout_3.addWidget(self.trigger_off_rb)
        self.frequency_gb = QtWidgets.QGroupBox(self.dockWidgetContents_3)
        self.frequency_gb.setGeometry(QtCore.QRect(563, 0, 176, 129))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frequency_gb.sizePolicy().hasHeightForWidth())
        self.frequency_gb.setSizePolicy(sizePolicy)
        self.frequency_gb.setMinimumSize(QtCore.QSize(160, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.frequency_gb.setFont(font)
        self.frequency_gb.setAlignment(QtCore.Qt.AlignCenter)
        self.frequency_gb.setObjectName("frequency_gb")
        self.layoutWidget_4 = QtWidgets.QWidget(self.frequency_gb)
        self.layoutWidget_4.setGeometry(QtCore.QRect(10, 30, 159, 52))
        self.layoutWidget_4.setObjectName("layoutWidget_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.layoutWidget_4)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.frequency_lcd = QtWidgets.QLCDNumber(self.layoutWidget_4)
        self.frequency_lcd.setMinimumSize(QtCore.QSize(75, 50))
        self.frequency_lcd.setMaximumSize(QtCore.QSize(75, 50))
        self.frequency_lcd.setBaseSize(QtCore.QSize(75, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.frequency_lcd.setFont(font)
        self.frequency_lcd.setSmallDecimalPoint(False)
        self.frequency_lcd.setDigitCount(4)
        self.frequency_lcd.setProperty("intValue", 0)
        self.frequency_lcd.setObjectName("frequency_lcd")
        self.horizontalLayout_4.addWidget(self.frequency_lcd)
        self.frequency_dial = QtWidgets.QDial(self.layoutWidget_4)
        self.frequency_dial.setMinimumSize(QtCore.QSize(50, 50))
        self.frequency_dial.setMaximumSize(QtCore.QSize(50, 50))
        self.frequency_dial.setMinimum(0)
        self.frequency_dial.setMaximum(10)
        self.frequency_dial.setSingleStep(1)
        self.frequency_dial.setPageStep(10)
        self.frequency_dial.setProperty("value", 10)
        self.frequency_dial.setWrapping(False)
        self.frequency_dial.setNotchesVisible(False)
        self.frequency_dial.setObjectName("frequency_dial")
        self.horizontalLayout_4.addWidget(self.frequency_dial, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.bandwidth_gb = QtWidgets.QGroupBox(self.dockWidgetContents_3)
        self.bandwidth_gb.setGeometry(QtCore.QRect(746, 0, 176, 129))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bandwidth_gb.sizePolicy().hasHeightForWidth())
        self.bandwidth_gb.setSizePolicy(sizePolicy)
        self.bandwidth_gb.setMinimumSize(QtCore.QSize(160, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.bandwidth_gb.setFont(font)
        self.bandwidth_gb.setAlignment(QtCore.Qt.AlignCenter)
        self.bandwidth_gb.setCheckable(True)
        self.bandwidth_gb.setObjectName("bandwidth_gb")
        self.layoutWidget = QtWidgets.QWidget(self.bandwidth_gb)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 30, 159, 52))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.bandwidth_lcd = QtWidgets.QLCDNumber(self.layoutWidget)
        self.bandwidth_lcd.setMinimumSize(QtCore.QSize(75, 50))
        self.bandwidth_lcd.setMaximumSize(QtCore.QSize(75, 50))
        self.bandwidth_lcd.setBaseSize(QtCore.QSize(75, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.bandwidth_lcd.setFont(font)
        self.bandwidth_lcd.setSmallDecimalPoint(False)
        self.bandwidth_lcd.setDigitCount(4)
        self.bandwidth_lcd.setSegmentStyle(QtWidgets.QLCDNumber.Filled)
        self.bandwidth_lcd.setProperty("intValue", 0)
        self.bandwidth_lcd.setObjectName("bandwidth_lcd")
        self.horizontalLayout_2.addWidget(self.bandwidth_lcd)
        self.bandwidth_dial = QtWidgets.QDial(self.layoutWidget)
        self.bandwidth_dial.setMinimumSize(QtCore.QSize(50, 50))
        self.bandwidth_dial.setMaximumSize(QtCore.QSize(50, 50))
        self.bandwidth_dial.setMaximum(10)
        self.bandwidth_dial.setSingleStep(1)
        self.bandwidth_dial.setPageStep(10)
        self.bandwidth_dial.setProperty("value", 10)
        self.bandwidth_dial.setWrapping(False)
        self.bandwidth_dial.setNotchesVisible(False)
        self.bandwidth_dial.setObjectName("bandwidth_dial")
        self.horizontalLayout_2.addWidget(self.bandwidth_dial)
        self.widget1 = QtWidgets.QWidget(self.bandwidth_gb)
        self.widget1.setGeometry(QtCore.QRect(22, 95, 133, 22))
        self.widget1.setObjectName("widget1")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.widget1)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_2 = QtWidgets.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_7.addWidget(self.label_2)
        self.ramp_up_rb = QtWidgets.QRadioButton(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.ramp_up_rb.setFont(font)
        self.ramp_up_rb.setText("Up")
        self.ramp_up_rb.setChecked(True)
        self.ramp_up_rb.setObjectName("ramp_up_rb")
        self.horizontalLayout_7.addWidget(self.ramp_up_rb)
        self.ramp_dn_rb = QtWidgets.QRadioButton(self.widget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ramp_dn_rb.sizePolicy().hasHeightForWidth())
        self.ramp_dn_rb.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.ramp_dn_rb.setFont(font)
        self.ramp_dn_rb.setText("Dn")
        self.ramp_dn_rb.setObjectName("ramp_dn_rb")
        self.horizontalLayout_7.addWidget(self.ramp_dn_rb)
        self.radar_controls_group.setWidget(self.dockWidgetContents_3)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(4), self.radar_controls_group)
        self.dsp_controls_group = QtWidgets.QDockWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dsp_controls_group.sizePolicy().hasHeightForWidth())
        self.dsp_controls_group.setSizePolicy(sizePolicy)
        self.dsp_controls_group.setMinimumSize(QtCore.QSize(360, 160))
        self.dsp_controls_group.setMaximumSize(QtCore.QSize(360, 160))
        self.dsp_controls_group.setFeatures(QtWidgets.QDockWidget.DockWidgetFloatable|QtWidgets.QDockWidget.DockWidgetMovable)
        self.dsp_controls_group.setAllowedAreas(QtCore.Qt.BottomDockWidgetArea|QtCore.Qt.TopDockWidgetArea)
        self.dsp_controls_group.setObjectName("dsp_controls_group")
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.groupBox = QtWidgets.QGroupBox(self.dockWidgetContents)
        self.groupBox.setGeometry(QtCore.QRect(7, 0, 144, 131))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMinimumSize(QtCore.QSize(140, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.groupBox.setFont(font)
        self.groupBox.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox.setObjectName("groupBox")
        self.widget2 = QtWidgets.QWidget(self.groupBox)
        self.widget2.setGeometry(QtCore.QRect(12, 24, 121, 101))
        self.widget2.setObjectName("widget2")
        self.formLayout = QtWidgets.QFormLayout(self.widget2)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.pulse_raw_rb = QtWidgets.QRadioButton(self.widget2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.pulse_raw_rb.setFont(font)
        self.pulse_raw_rb.setObjectName("pulse_raw_rb")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.pulse_raw_rb)
        self.pulse_debias_rb = QtWidgets.QRadioButton(self.widget2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.pulse_debias_rb.setFont(font)
        self.pulse_debias_rb.setChecked(True)
        self.pulse_debias_rb.setObjectName("pulse_debias_rb")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.SpanningRole, self.pulse_debias_rb)
        self.pulse_mti_rb = QtWidgets.QRadioButton(self.widget2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.pulse_mti_rb.setFont(font)
        self.pulse_mti_rb.setObjectName("pulse_mti_rb")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.pulse_mti_rb)
        self.pulse_mti_cb = QtWidgets.QComboBox(self.widget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pulse_mti_cb.sizePolicy().hasHeightForWidth())
        self.pulse_mti_cb.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.pulse_mti_cb.setFont(font)
        self.pulse_mti_cb.setObjectName("pulse_mti_cb")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.pulse_mti_cb)
        self.pulse_filter_ck = QtWidgets.QCheckBox(self.widget2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.pulse_filter_ck.setFont(font)
        self.pulse_filter_ck.setObjectName("pulse_filter_ck")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.pulse_filter_ck)
        self.pulse_filter_cb = QtWidgets.QComboBox(self.widget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pulse_filter_cb.sizePolicy().hasHeightForWidth())
        self.pulse_filter_cb.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.pulse_filter_cb.setFont(font)
        self.pulse_filter_cb.setObjectName("pulse_filter_cb")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.pulse_filter_cb)
        self.groupBox_2 = QtWidgets.QGroupBox(self.dockWidgetContents)
        self.groupBox_2.setGeometry(QtCore.QRect(158, 0, 191, 131))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setMinimumSize(QtCore.QSize(140, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_2.setObjectName("groupBox_2")
        self.spinBox_3 = QtWidgets.QSpinBox(self.groupBox_2)
        self.spinBox_3.setGeometry(QtCore.QRect(230, 30, 42, 22))
        self.spinBox_3.setObjectName("spinBox_3")
        self.label = QtWidgets.QLabel(self.groupBox_2)
        self.label.setGeometry(QtCore.QRect(8, 25, 59, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.spectrum_window_cb = QtWidgets.QComboBox(self.groupBox_2)
        self.spectrum_window_cb.setGeometry(QtCore.QRect(103, 25, 80, 22))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spectrum_window_cb.sizePolicy().hasHeightForWidth())
        self.spectrum_window_cb.setSizePolicy(sizePolicy)
        self.spectrum_window_cb.setMinimumSize(QtCore.QSize(80, 0))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.spectrum_window_cb.setFont(font)
        self.spectrum_window_cb.setObjectName("spectrum_window_cb")
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setGeometry(QtCore.QRect(8, 54, 88, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setMinimumSize(QtCore.QSize(70, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.spectrum_oversample_cb = QtWidgets.QComboBox(self.groupBox_2)
        self.spectrum_oversample_cb.setGeometry(QtCore.QRect(103, 54, 80, 22))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spectrum_oversample_cb.sizePolicy().hasHeightForWidth())
        self.spectrum_oversample_cb.setSizePolicy(sizePolicy)
        self.spectrum_oversample_cb.setMinimumSize(QtCore.QSize(80, 0))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.spectrum_oversample_cb.setFont(font)
        self.spectrum_oversample_cb.setObjectName("spectrum_oversample_cb")
        self.spectrum_xscale_hz_rb = QtWidgets.QRadioButton(self.groupBox_2)
        self.spectrum_xscale_hz_rb.setGeometry(QtCore.QRect(59, 84, 46, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.spectrum_xscale_hz_rb.setFont(font)
        self.spectrum_xscale_hz_rb.setText("Hz")
        self.spectrum_xscale_hz_rb.setChecked(False)
        self.spectrum_xscale_hz_rb.setObjectName("spectrum_xscale_hz_rb")
        self.spectrum_xscale_m_rb = QtWidgets.QRadioButton(self.groupBox_2)
        self.spectrum_xscale_m_rb.setGeometry(QtCore.QRect(106, 84, 90, 25))
        self.spectrum_xscale_m_rb.setMinimumSize(QtCore.QSize(90, 0))
        self.spectrum_xscale_m_rb.setMaximumSize(QtCore.QSize(90, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.spectrum_xscale_m_rb.setFont(font)
        self.spectrum_xscale_m_rb.setText("m or m/s")
        self.spectrum_xscale_m_rb.setChecked(True)
        self.spectrum_xscale_m_rb.setObjectName("spectrum_xscale_m_rb")
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setGeometry(QtCore.QRect(10, 86, 54, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.dsp_controls_group.setWidget(self.dockWidgetContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(8), self.dsp_controls_group)
        self.collection_controls_group = QtWidgets.QDockWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.collection_controls_group.sizePolicy().hasHeightForWidth())
        self.collection_controls_group.setSizePolicy(sizePolicy)
        self.collection_controls_group.setMinimumSize(QtCore.QSize(480, 160))
        self.collection_controls_group.setMaximumSize(QtCore.QSize(480, 160))
        self.collection_controls_group.setFeatures(QtWidgets.QDockWidget.DockWidgetFloatable|QtWidgets.QDockWidget.DockWidgetMovable)
        self.collection_controls_group.setAllowedAreas(QtCore.Qt.BottomDockWidgetArea|QtCore.Qt.TopDockWidgetArea)
        self.collection_controls_group.setObjectName("collection_controls_group")
        self.dockWidgetContents_4 = QtWidgets.QWidget()
        self.dockWidgetContents_4.setObjectName("dockWidgetContents_4")
        self.collection_toggle_pb = QtWidgets.QPushButton(self.dockWidgetContents_4)
        self.collection_toggle_pb.setEnabled(True)
        self.collection_toggle_pb.setGeometry(QtCore.QRect(356, 102, 121, 28))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.collection_toggle_pb.setFont(font)
        self.collection_toggle_pb.setCheckable(True)
        self.collection_toggle_pb.setObjectName("collection_toggle_pb")
        self.sar_trigger_gb = QtWidgets.QGroupBox(self.dockWidgetContents_4)
        self.sar_trigger_gb.setGeometry(QtCore.QRect(356, 0, 120, 101))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.sar_trigger_gb.setFont(font)
        self.sar_trigger_gb.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.sar_trigger_gb.setCheckable(True)
        self.sar_trigger_gb.setChecked(False)
        self.sar_trigger_gb.setObjectName("sar_trigger_gb")
        self.label_13 = QtWidgets.QLabel(self.sar_trigger_gb)
        self.label_13.setGeometry(QtCore.QRect(10, 50, 41, 18))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_13.setFont(font)
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.sar_trigger_dx_sb = QtWidgets.QDoubleSpinBox(self.sar_trigger_gb)
        self.sar_trigger_dx_sb.setGeometry(QtCore.QRect(58, 50, 51, 18))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.sar_trigger_dx_sb.setFont(font)
        self.sar_trigger_dx_sb.setMinimum(1.0)
        self.sar_trigger_dx_sb.setMaximum(10.0)
        self.sar_trigger_dx_sb.setProperty("value", 2.54)
        self.sar_trigger_dx_sb.setObjectName("sar_trigger_dx_sb")
        self.label_14 = QtWidgets.QLabel(self.sar_trigger_gb)
        self.label_14.setGeometry(QtCore.QRect(10, 75, 41, 18))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_14.setFont(font)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.sar_trigger_pace_cb = QtWidgets.QComboBox(self.sar_trigger_gb)
        self.sar_trigger_pace_cb.setGeometry(QtCore.QRect(58, 75, 51, 18))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.sar_trigger_pace_cb.setFont(font)
        self.sar_trigger_pace_cb.setObjectName("sar_trigger_pace_cb")
        self.label_11 = QtWidgets.QLabel(self.sar_trigger_gb)
        self.label_11.setGeometry(QtCore.QRect(10, 24, 41, 19))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_11.setFont(font)
        self.label_11.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.sar_trigger_steps_sb = QtWidgets.QSpinBox(self.sar_trigger_gb)
        self.sar_trigger_steps_sb.setGeometry(QtCore.QRect(58, 24, 51, 19))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.sar_trigger_steps_sb.setFont(font)
        self.sar_trigger_steps_sb.setSuffix("")
        self.sar_trigger_steps_sb.setMinimum(1)
        self.sar_trigger_steps_sb.setMaximum(250)
        self.sar_trigger_steps_sb.setProperty("value", 1)
        self.sar_trigger_steps_sb.setObjectName("sar_trigger_steps_sb")
        self.collect_progress_bar = QtWidgets.QProgressBar(self.dockWidgetContents_4)
        self.collect_progress_bar.setGeometry(QtCore.QRect(10, 106, 341, 21))
        self.collect_progress_bar.setProperty("value", 24)
        self.collect_progress_bar.setTextVisible(False)
        self.collect_progress_bar.setObjectName("collect_progress_bar")
        self.record_data_gb = QtWidgets.QGroupBox(self.dockWidgetContents_4)
        self.record_data_gb.setGeometry(QtCore.QRect(10, 0, 341, 101))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.record_data_gb.setFont(font)
        self.record_data_gb.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.record_data_gb.setCheckable(True)
        self.record_data_gb.setChecked(False)
        self.record_data_gb.setObjectName("record_data_gb")
        self.layoutWidget1 = QtWidgets.QWidget(self.record_data_gb)
        self.layoutWidget1.setGeometry(QtCore.QRect(11, 26, 321, 66))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.layoutWidget1)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_19 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_19.setFont(font)
        self.label_19.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName("label_19")
        self.gridLayout_2.addWidget(self.label_19, 0, 0, 1, 1)
        self.record_data_duration_sb = QtWidgets.QSpinBox(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.record_data_duration_sb.setFont(font)
        self.record_data_duration_sb.setMaximum(3600)
        self.record_data_duration_sb.setObjectName("record_data_duration_sb")
        self.gridLayout_2.addWidget(self.record_data_duration_sb, 0, 1, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_20.setFont(font)
        self.label_20.setAlignment(QtCore.Qt.AlignCenter)
        self.label_20.setObjectName("label_20")
        self.gridLayout_2.addWidget(self.label_20, 0, 2, 1, 1)
        self.record_data_format_cb = QtWidgets.QComboBox(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.record_data_format_cb.setFont(font)
        self.record_data_format_cb.setObjectName("record_data_format_cb")
        self.gridLayout_2.addWidget(self.record_data_format_cb, 0, 3, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(True)
        self.label_21.setFont(font)
        self.label_21.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_21.setAlignment(QtCore.Qt.AlignCenter)
        self.label_21.setObjectName("label_21")
        self.gridLayout_2.addWidget(self.label_21, 1, 0, 1, 1)
        self.record_data_filename_le = QtWidgets.QLineEdit(self.layoutWidget1)
        self.record_data_filename_le.setObjectName("record_data_filename_le")
        self.gridLayout_2.addWidget(self.record_data_filename_le, 1, 1, 1, 2)
        self.record_data_browse_pb = QtWidgets.QPushButton(self.layoutWidget1)
        self.record_data_browse_pb.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(True)
        self.record_data_browse_pb.setFont(font)
        self.record_data_browse_pb.setObjectName("record_data_browse_pb")
        self.gridLayout_2.addWidget(self.record_data_browse_pb, 1, 3, 1, 1)
        self.collection_controls_group.setWidget(self.dockWidgetContents_4)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(8), self.collection_controls_group)
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.menuFile.addAction(self.actionQuit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Teensy USB Radar Control"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.if_voltage_tab), _translate("MainWindow", "IF Voltage"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.if_spectrum_tab), _translate("MainWindow", "IF Spectum"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.if_waterfall_tab), _translate("MainWindow", "Waterfall Spectrum"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.log_messages_tab), _translate("MainWindow", "Log Messages"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.radar_controls_group.setWindowTitle(_translate("MainWindow", "Radar Controls"))
        self.gain_gb_2.setTitle(_translate("MainWindow", "COM Port"))
        self.connect_pb.setText(_translate("MainWindow", "Connect"))
        self.gain_gb.setTitle(_translate("MainWindow", "Voltage Gain"))
        self.pulse_length_gb.setTitle(_translate("MainWindow", "Pulse Length (ms)"))
        self.label_4.setText(_translate("MainWindow", "Trigger"))
        self.frequency_gb.setTitle(_translate("MainWindow", "Center Frequency (MHz)"))
        self.bandwidth_gb.setTitle(_translate("MainWindow", "Bandwidth (MHz)"))
        self.label_2.setText(_translate("MainWindow", "Ramp"))
        self.dsp_controls_group.setWindowTitle(_translate("MainWindow", "DSP Controls"))
        self.groupBox.setTitle(_translate("MainWindow", "Pulse Processing"))
        self.pulse_raw_rb.setText(_translate("MainWindow", "Raw"))
        self.pulse_debias_rb.setText(_translate("MainWindow", "Debias"))
        self.pulse_mti_rb.setText(_translate("MainWindow", "MTI"))
        self.pulse_filter_ck.setText(_translate("MainWindow", "Filter"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Spectrum Processing"))
        self.label.setText(_translate("MainWindow", "Window"))
        self.label_6.setText(_translate("MainWindow", "Oversample"))
        self.label_5.setText(_translate("MainWindow", "X Scale"))
        self.collection_controls_group.setWindowTitle(_translate("MainWindow", "Collection Controls"))
        self.collection_toggle_pb.setText(_translate("MainWindow", "Start"))
        self.sar_trigger_gb.setTitle(_translate("MainWindow", "SAR Trigger"))
        self.label_13.setText(_translate("MainWindow", "dx"))
        self.label_14.setText(_translate("MainWindow", "Pace"))
        self.label_11.setText(_translate("MainWindow", "Steps"))
        self.record_data_gb.setTitle(_translate("MainWindow", "Record Data"))
        self.label_19.setText(_translate("MainWindow", "Duration"))
        self.label_20.setText(_translate("MainWindow", "Format"))
        self.label_21.setText(_translate("MainWindow", "Filename"))
        self.record_data_browse_pb.setText(_translate("MainWindow", "Browse"))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))
from RadarWidgets import IFSpectrumPlotWidget, IFVoltagePlotWidget, IFWaterfallPlotWidget
#     Copyright (C) 2020 MASSACHUSETTS INSTITUTE OF TECHNOLOGY
